In [1]:
import numpy as np

In [4]:
import pandas as pd

df = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

Пусть в первой квартире один просмотр занимает 10 минут, во второй — 20 минут, в третьей — полчаса, в четверой — 15 минут, в пятой — 5 минут, в шестой — 40 минут, в седьмой — 20 минут, в восьмой — 8 минут и в девятой — 20 минут.

Найдите продолжительность просмотров в минутах во всех квартирах за две недели.

In [14]:
time_vec = np.array([10, 20, 30 , 15, 5 , 40, 20, 8, 20])
time_vec @ df['5.Demo two weeks'].values


1348

In [15]:
Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

In [17]:
Inc = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income]).T
Inc

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

In [18]:
Cons = np.array([Husband_Consumption, Wife_Consumption, Mother_In_Law_Consumption]).T
Cons

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

In [19]:
0.87*Inc

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

In [21]:
0.87*Inc - Cons

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

In [22]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])


In [24]:
B@A

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [25]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

In [27]:
X = np.array([x, y, z])
X.T@X

array([[ 6,  3,  0,  2,  4],
       [ 3,  6,  0,  1,  8],
       [ 0,  0,  3, -1,  4],
       [ 2,  1, -1,  1,  0],
       [ 4,  8,  4,  0, 16]])

In [32]:
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

In [49]:
Price_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                2.0              1.5          1.0      0.8   1.0
Борис              1.8              2.5          1.0      1.0   1.0
Вика               2.0              2.0          0.0      0.5   2.0
Галя               1.8              1.2          2.8      0.8   2.0
Дима               2.5              3.5          2.0      1.0   1.5
Егор               5.0              5.0          3.0      2.0   2.5
Женя               1.1              1.0          1.5      0.5   1.7
Юра                4.5              4.0          2.5      1.0   2.0

In [45]:
Count_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                 10                5           12       15    10
Борис                2               21            3       25     6
Вика                12               12            0       30     4
Галя                 4                8           18       14     5
Дима                 6               25           27       25    18
Егор                10                3            2       17    12
Женя                22                1            4       25    20
Юра                  7                0           31       31    28

In [39]:
C = Count_DF.values
P = Price_DF.values


In [59]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [61]:
P*C

array([[20. ,  7.5, 12. , 12. , 10. ],
       [ 3.6, 52.5,  3. , 25. ,  6. ],
       [24. , 24. ,  0. , 15. ,  8. ],
       [ 7.2,  9.6, 50.4, 11.2, 10. ],
       [15. , 87.5, 54. , 25. , 27. ],
       [50. , 15. ,  6. , 34. , 30. ],
       [24.2,  1. ,  6. , 12.5, 34. ],
       [31.5,  0. , 77.5, 31. , 56. ]])

In [60]:
P*C @ (np.ones(5) - com)

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

In [43]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

(8, 8)

In [48]:
F

array([[20. ,  7.5, 12. , 12. , 10. ],
       [ 3.6, 52.5,  3. , 25. ,  6. ],
       [24. , 24. ,  0. , 15. ,  8. ],
       [ 7.2,  9.6, 50.4, 11.2, 10. ],
       [15. , 87.5, 54. , 25. , 27. ],
       [50. , 15. ,  6. , 34. , 30. ],
       [24.2,  1. ,  6. , 12.5, 34. ],
       [31.5,  0. , 77.5, 31. , 56. ]])

In [62]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])


In [69]:
np.linalg.inv(A)

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

In [71]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

In [80]:
arr = np.array([v1,v2,v3,v4]).T
arr

array([[ 9,  2,  4,  3],
       [10,  0,  0, -4],
       [ 7,  5,  0,  3],
       [ 7,  1,  4, -1],
       [ 9,  4,  1, -4]])

In [82]:
np.linalg.matrix_rank(arr)

4

In [85]:
np.linalg.inv(arr.T @ arr)

array([[ 0.01711488, -0.02798543, -0.02623063,  0.01599775],
       [-0.02798543,  0.071967  ,  0.03031441, -0.02722776],
       [-0.02623063,  0.03031441,  0.07683106, -0.02640498],
       [ 0.01599775, -0.02722776, -0.02640498,  0.03479318]])

# OLS

$ \left\{\begin{array}{c}
w_1+2 w_2=1 \\
-3 w_1+w_2=4 \\
w_1+2 w_2=5 \\
w_1-w_2=0
\end{array}\right. $

In [88]:
A = np.array(
    [[1,2],
     [-3, 1],
     [1,2],
     [1,-1]]
)
b = np.array([1,4,5,0])

In [89]:
gramm_cols = A.T @A

array([[12,  0],
       [ 0, 10]])

In [90]:
w = np.linalg.inv(gramm_cols)@ A.T @ b

In [91]:
w

array([-0.5,  1.6])

In [94]:
import numpy as np # для работы с массивами
import pandas as pd # для работы с DataFrame 
from sklearn import datasets # для импорта данных
import seaborn as sns # для визуализации статистических данных
import matplotlib.pyplot as plt # для построения графиков

# загружаем датасет
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'PRICE']
boston_data = pd.read_csv('housing.csv', header=None, delimiter=r"\s+", names=column_names)
boston_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  PRICE  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

In [96]:
A = np.column_stack((np.ones(506), boston_data[['CHAS', 'LSTAT', 'CRIM','RM']]))
y = boston_data[['PRICE']]
# вычисляем OLS-оценку для коэффициентов без стандартизации
w_hat=np.linalg.inv(A.T@A)@A.T@y
print(w_hat.values)

[[-1.92052548]
 [ 3.9975594 ]
 [-0.58240212]
 [-0.09739445]
 [ 5.07554248]]


In [111]:
# составляем матрицу наблюдений без дополнительного столбца из единиц
A = boston_data[['CHAS', 'LSTAT', 'CRIM','RM']]
y = boston_data[['PRICE']]
# стандартизируем векторы в столбцах матрицы A
A_cent = A - A.mean()
A_st = A_cent/np.linalg.norm(A_cent, axis=0)
A_st.describe().round(2)

CHAS   LSTAT    CRIM      RM
count  506.00  506.00  506.00  506.00
mean    -0.00   -0.00   -0.00   -0.00
std      0.04    0.04    0.04    0.04
min     -0.01   -0.07   -0.02   -0.17
25%     -0.01   -0.04   -0.02   -0.03
50%     -0.01   -0.01   -0.02   -0.00
75%     -0.01    0.03    0.00    0.02
max      0.16    0.16    0.44    0.16

In [112]:
# стандартизируем вектор целевой переменной
y_cent = y - y.mean()
y_st = y_cent/np.linalg.norm(y_cent)

In [113]:
# вычислим OLS-оценку для стандартизированных коэффициентов
w_hat_st=np.linalg.inv(A_st.T@A_st)@A_st.T@y_st
print(w_hat_st.values)

[[ 0.11039956]
 [-0.45220423]
 [-0.09108766]
 [ 0.38774848]]


In [114]:
# матрица Грама
A_st.T @ A_st

CHAS     LSTAT      CRIM        RM
CHAS   1.000000 -0.053929 -0.055892  0.091251
LSTAT -0.053929  1.000000  0.455621 -0.613808
CRIM  -0.055892  0.455621  1.000000 -0.219247
RM     0.091251 -0.613808 -0.219247  1.000000

In [117]:
v = np.array([5,1,2])
u = np.array([4,2,8])
v_cnt = v - v.mean()
u_cnt = u - u.mean()
corr_coef = np.dot(v_cnt/np.linalg.norm(v_cnt), u_cnt/np.linalg.norm(u_cnt))
corr_coef

0.052414241836095915

In [120]:
x = np.array([5.1, 1.8, 2.1, 10.3, 12.1, 12.6])
y = np.array([10.2, 3.7, 4.1, 20.5, 24.2, 24.1])
z = np.array([2.5, 0.9, 1.1, 5.1, 6.1, 6.3])
corr_mtx = np.corrcoef([x,y,z])
corr_mtx

array([[1.        , 0.99925473, 0.99983661],
       [0.99925473, 1.        , 0.99906626],
       [0.99983661, 0.99906626, 1.        ]])

In [121]:
np.linalg.matrix_rank(corr_mtx)

3

In [122]:
np.linalg.det(corr_mtx)

4.862298229241645e-07

In [68]:
A = np.array([
    [1,3,5],
    [4,-4,9],
    [3,6,10]
])
np.linalg.eig(A)

(array([14.91929433, -0.42008185, -7.49921248]),
 array([[-0.38633497, -0.92425394,  0.15847599],
        [-0.46156184, -0.14860787, -0.94200643],
        [-0.79856494,  0.35166797,  0.29581963]]))

In [8]:
A = np.array([
    [1,9,4],
    [9,4,7],
    [4,7,12]
])
np.linalg.eig(A.T@A)

(array([391.37004987,  45.77088847,  15.85906166]),
 array([[-0.41955589, -0.7323045 , -0.5363795 ],
        [-0.55709648,  0.67425896, -0.48478693],
        [-0.71667034, -0.09541992,  0.69085358]]))

In [74]:
A = np.array([
    [1, 0.8],
    [0.8, 1]
])  
np.linalg.eig(A)

(array([1.8, 0.2]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

PCA

In [84]:
corr

array([[1.        , 0.99220261],
       [0.99220261, 1.        ]])

In [78]:
x_1 = np.array([1,2,1,1])
x_2 = np.array([70, 130, 65, 60])
A = np.column_stack((x_1,x_2))
corr = np.corrcoef(A, rowvar=False)

eigh, eigh_v = np.linalg.eig(corr)
print(list(zip(eigh, eigh_v)))

[(1.9922026100638295, array([ 0.70710678, -0.70710678])), (0.007797389936170407, array([0.70710678, 0.70710678]))]


In [87]:
A - A.mean(axis=0)

array([[ -0.25, -11.25],
       [  0.75,  48.75],
       [ -0.25, -16.25],
       [ -0.25, -21.25]])

In [94]:
A_std = (A - A.mean(axis=0)) / np.linalg.norm(A - A.mean(axis=0), axis=0)
pca_1 = eigh_v[0][0] * A_std[:,0] + eigh_v[1][0] * A_std[:, 1]
pca_1 = pca_1/ np.linalg.norm(pca_1)
pca_1

array([-0.24396044,  0.86433557, -0.28811186, -0.33226327])